name: csharpier-format-check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  csharpier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hypermania

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dotnet tools (Hypermania tool-manifest)
        run: dotnet tool restore

      - name: CSharpier check
        run: dotnet csharpier check .

